# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banking_system.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62\x61nking_system.proto\"Y\n\x10Transfer_Request\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x16\n\x0eoperation_type\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x11\n\tpropagate\x18\x04 \x01(\x08\"G\n\x11Transfer_Response\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x03\x32G\n\x08Transfer\x12;\n\x10message_delivery\x12\x11.Transfer_Request\x1a\x12.Transfer_Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSFER_REQUEST']._serialized_start=24
  _globals['_TRANSFER_REQUEST']._serialized_end=113
  _globals['_TRANSFER_RESPONSE']._serialized_start=115
  _globals['_TRANSFER_RESPONSE']._serialized_end=186
  _globals['_TRANSFER']._serialized_start=188
  _globals['_TRANSFER']._serialized_end=259
# @@protoc_insertion_point(module_scope)
