# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import banking_system_pb2 as banking__system__pb2


class TransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.message_delivery = channel.unary_unary(
                '/Transfer/message_delivery',
                request_serializer=banking__system__pb2.Transfer_Request.SerializeToString,
                response_deserializer=banking__system__pb2.Transfer_Response.FromString,
                )


class TransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def message_delivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'message_delivery': grpc.unary_unary_rpc_method_handler(
                    servicer.message_delivery,
                    request_deserializer=banking__system__pb2.Transfer_Request.FromString,
                    response_serializer=banking__system__pb2.Transfer_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def message_delivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transfer/message_delivery',
            banking__system__pb2.Transfer_Request.SerializeToString,
            banking__system__pb2.Transfer_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
